### ISSUE TITLE
이미 번역중인 웹사이트 존재

### ISSUE THREAD

**Issue by ghost** [techhtml/website#26]
이쪽 도메인
https://flutter-ko.dev
조형재님이 관리중인 도메인
https://flutter-kr.io

초반부만 번역이 진행된 상태라서 사람들이 많이 보는 것 같지는 않지만,
추후 혼선 방지를 위해서 해당 사이트 관리자와 연락을 통해 한 쪽으로 통폐합하는게 좋을 것 같습니다 :)

**Comment by techhtml** [comment]
안녕하세요.
조형재님의 GitHub 계정을 알려주시거나 메일 주소를 알려주시면 연락을 취하도록 하겠습니다.

**Comment by ghost** [comment]
https://github.com/bro-jo
여기에 나와있는 이메일 참고하면 될 것 같습니다 ㅎㅎ

**Comment by techhtml** [comment]
이 저장소로 합치기로 하였습니다!
제보 고맙습니다.
